# Distributed under the MIT License.
# See LICENSE.txt for details.

name: Demo Container

on:
  workflow_dispatch:

  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker:
    name: Build and push 'demo' image to DockerHub
    runs-on: ubuntu-latest
    environment: deploy-containers
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up emulation support
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: "./containers/Dockerfile.buildenv"
          target: demo
          tags: sxscollaboration/spectre:latest,sxscollaboration/spectre:demo
          platforms: linux/amd64,linux/arm64

